// File generated by FlutLab.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'try to add using FlutLab Firebase Configuration',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: 'AIzaSyBYG2w_rU5snR3CLT1ajZbK7f_XJchxD0w',
      authDomain: 'praktikum-mobileapp-e3b63.firebaseapp.com',
      databaseURL:
          'https://praktikum-mobileapp-e3b63-default-rtdb.asia-southeast1.firebasedatabase.app',
      projectId: 'praktikum-mobileapp-e3b63',
      storageBucket: 'praktikum-mobileapp-e3b63.firebasestorage.app',
      messagingSenderId: '286022466212',
      appId: '1:286022466212:web:4e5d4fb279365570cd4431');

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: 'AIzaSyAV6_YtRXa7K-dTThBEjH5ceWSJUmiZDaU',
      appId: '1:286022466212:android:6ea062adcca18220cd4431',
      messagingSenderId: '286022466212',
      projectId: 'praktikum-mobileapp-e3b63',
      databaseURL:
          'https://praktikum-mobileapp-e3b63-default-rtdb.asia-southeast1.firebasedatabase.app',
      storageBucket: 'praktikum-mobileapp-e3b63.firebasestorage.app');
}
